### PR TITLE
Fix compat with cohttp 0.18.0

### PR DESCRIPTION
**Pull request by rgrinberg**
sorry all, I somehow missed this.

 @samoht @talex5

### CODE REVIEW

**Comment by talex5** [comment]
Travis is failing with `Unbound type constructor Conduit_mirage.t`. Needs a restriction on conduit too?

**Comment by samoht** [comment]
need to add mirage-dev as a remote

**Comment by avsm** [comment]
please dont add just add mirage-dev as a remote -- the lower bounds should work with stable. If it fails with an unsatisfiable constraint, then you need mirage-dev.

**Comment by samoht** [comment]
so we need to wait the release of conduit before merging that PR (not sure to understand what you mean @avsm).

**Comment by samoht** [comment]
Superseded by #13

**Pull request closed without merging**
